# Generated by Django 4.2 on 2023-06-19 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='genre',
            field=models.JSONField(default=list),
        ),
    ]
