# Generated by Django 4.2 on 2023-06-19 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime_list', '0002_alter_anime_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='rating',
        ),
    ]
