# Generated by Django 4.2 on 2023-06-19 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_list', '0003_remove_anime_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='image',
            field=models.ImageField(upload_to='anime_list/anime_imgs/'),
        ),
    ]
