# Generated by Django 4.2 on 2023-06-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_profile_cover_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_premium',
            field=models.BooleanField(default='Free', verbose_name='Es usuario premium'),
        ),
    ]
