# Generated by Django 4.2 on 2023-06-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_is_premium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_premium',
            field=models.BooleanField(default=False, verbose_name='Es usuario premium'),
        ),
    ]
