# Generated by Django 4.2 on 2023-06-15 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_is_premium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='premium_type',
            field=models.CharField(default='Free', max_length=20, verbose_name='Tipo de suscripción'),
        ),
    ]
