# Generated by Django 4.2 on 2023-06-19 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_email'),
        ('users', '0006_alter_user_premium_type'),
    ]

    operations = [
    ]
