# Generated by Django 4.2 on 2023-06-19 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('episodes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='genre',
        ),
    ]
