# Generated by Django 4.2 on 2023-06-19 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime_list', '0002_alter_anime_genre'),
        ('episodes', '0002_remove_episode_genre'),
        ('anime_genre', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
